<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VCQHI407" failures="2" tests="15" name="Command line test" time="1.985" errors="0" timestamp="2023-07-09T12:11:14 IST">
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testApproveLoanApplication_Success" time="0.043"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testDeleteLoanApplication_Exception" time="0.014">
    <failure type="org.mockito.exceptions.base.MockitoException" message="
Checked exception is invalid for this method!
Invalid: java.lang.Exception">
      <![CDATA[org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.lang.Exception
at com.nkxgen.spring.jdbc.Test.LoanControllerTest.testDeleteLoanApplication_Exception(LoanControllerTest.java:273)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.nkxgen.spring.jdbc.Test.LoanControllerTestRunner.main(LoanControllerTestRunner.java:20)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteLoanApplication_Exception -->
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testDeleteLoanApplication_Success" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetAccountById_AccountNotFound" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetAccountById_Success" time="0.003"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetLoanAccounts_PermissionGranted" time="0.003"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetLoanApplicationById_ApplicationNotFound" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetLoanApplicationById_Success" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetLoanApplication_PermissionDenied" time="0.001"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testGetLoanApplication_PermissionGranted" time="0.006"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testLoanNewApplicationForm" time="0.001"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testNewLoanApplication_Success" time="0.004"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testRedirectForm" time="0.001"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testUpdateLoanApplication_Exception" time="0.001">
    <failure type="org.mockito.exceptions.base.MockitoException" message="
Checked exception is invalid for this method!
Invalid: java.lang.Exception">
      <![CDATA[org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.lang.Exception
at com.nkxgen.spring.jdbc.Test.LoanControllerTest.testUpdateLoanApplication_Exception(LoanControllerTest.java:170)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.nkxgen.spring.jdbc.Test.LoanControllerTestRunner.main(LoanControllerTestRunner.java:20)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateLoanApplication_Exception -->
  <testcase classname="com.nkxgen.spring.jdbc.Test.LoanControllerTest" name="testUpdateLoanApplication_Success" time="0.001"/>
</testsuite> <!-- Command line test -->
